### ISSUE TITLE
Stop simulation API should advice if it is not possible to wait

### ISSUE THREAD

**Issue by nicolapiccinelli** [CoppeliaRobotics/lua#3]
Hello,
I was looking at the source code of the Lua API to figure out how `stopSimulation` is implemented. If I'm getting right, the function if you are asking to wait from a context where is not possible, just ignore the argument and return. Wouldn't be better to return a state from the stop simulation? Or there is a function I can use before to check if the context is eligible to wait for stop completion?

https://github.com/CoppeliaRobotics/lua/blob/0dfac48b4706e1f6029bbe19580e965d905345e4/sim.lua#L83

**Comment by Coppelia** [comment]
@nicolapiccinelli, yes, that would be one possibility. But you could also use sim.getSimulationState to check if simulation is stopped after calling sim.stopSimulation
