### ISSUE TITLE
typo in clearBufferSignal in sim.lua

### ISSUE THREAD

**Issue by mfrigerio17** [CoppeliaRobotics/lua#4]
Hi,

I guess [this line](https://github.com/CoppeliaRobotics/lua/blob/fb51cf629e60c1538573e0d834da8a71097300ce/sim.lua#L37) should use

`clearStringSignal`

rather than `setClearStringSignal`.

I got a nil value error when attempting to call `sim.clearBufferSignal`

**Comment by Coppelia** [comment]
Thanks again @mfrigerio17!
Fixed!
